#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor DisplayPort-0 -d web msg music files V 
bspc monitor DVI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#boreder colors
bspc config focused_border_color "#B26CC0"
bspc config presel_feedback_color "#d8b4db"
bspc config top_padding 40

#define rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Auto start stuff


~/.config/polybar/launch.sh &
dunst ~/.config/dunst/dunstrc &
setxkbmap latam &
nitrogen --restore &
picom &
pulseaudio --start &

